### ISSUE TITLE
Problem with make

### ISSUE THREAD

**Issue by mattiabress** [yohhoy/heic2hevc#1]
Good morning
I have forked your repository because I want to implement your code with the new version of Nokia library. 
I want to implement the new version of Nokia because  I would like to extract the hevc video from  the new iPhone's photos taken by the newest iPhone.
In my linux installation your code doesn't work because i have problem related to the make file.

Can you give me some tips of to extract the hevc from the newst iphone phots, and how i can run you code in my linux enviroment

your help will be very appreciate

**Comment by yohhoy** [comment]
rel #2
